version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks: 
      - grafana_network
    volumes:
      - grafana-storage:/var/lib/grafana
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: grafana.mssql
    ports:
      - '1433:1433'
    networks: 
      - grafana_network
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=@a123456"

volumes:
  grafana-storage: {}

networks:
  grafana_network:
    external: true